[package]
name = "impl-b"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
impl-b-dep-with-features = { package = "dep-with-features", path = "../dep-with-features", features = ["b"] }